export const goods = {

    "10000": {
        "name": "ECCO Soft ZW5569",
        "price": 130,
        "description": "pokupaem new bransed shoes go check sizes and color id 10001",
        "category": "shoes",
        "brand" : "ECCO",
        "model" : "ZW5000",
        "color": ['red', 'grey'],
        "size": [37, 38, 39],
        "image": "../images/ZW5569.jpeg",
        "featured": true,
        "owl_carousel": false
    },
    "10001": {
        "name": "ECCO Soft ZW5680",
        "price": 120,
        "description": "pokupaem new bransed shoes go check sizes and color id 10001-1",
        "category": "shoes",
        "brand" : "ECCO",
        "model" : "ZW5000",
        "color": ['grey', 'red'],
        "size": [36, 40],
        "image": "../images/ZW5680.jpeg",
        "featured": false,
        "owl_carousel": true
    },

    "10002": {
        "name": "Levis T-shirt",
        "price": 70,
        "description": "try new Levis T-shirtt buy it very very good  buy it go go go some text try again 10002",
        "category": "t_shirt",
        "color": ['black', 'blue', 'white'],
        "size": ["L", "M"],
        "image": "../images/pic2.jpg",
        "featured": true,
        "owl_carousel": false
    },
    "10003": {
        "name": "True T-shirt",
        "price": 15,
        "description": "try new Branded t-shirt buy it very very good  buy it go go go some text try again 10003",
        "category": "t_shirt",
        "color": ['grey'],
        "size": ["L", "M"],
        "image": "../images/pic3.jpg",
        "featured": true,
        "owl_carousel": false
    },
    "10004": {
        "name": "Branded bags",
        "price": 25,
        "description": "very good wallet buy it go go go some text try again 10004",
        "category": "wallet",
        "color": ['brown'],
        "size": ["current"],
        "image": "../images/pic4.jpg",
        "featured": true,
        "owl_carousel": true
    },
    "10005": {
        "name": "EMS women bag",
        "price": 105,
        "description": "very good bag buy it go go go some text try again 10005",
        "category": "handbags",
        "color": ['coffee'],
        "size": ["current"],
        "image": "../images/pic5.jpg",
        "featured": true,
        "owl_carousel": true
    },
    "10006": {
        "name": "Easy top",
        "price": 10,
        "description": "try new Branded top shirt buy it very very good  buy it go go go some text try again 10006",
        "category": "t_shirt",
        "color": ['black'],
        "size": ["L", "S"],
        "image": "../images/pic6.jpg",
        "featured": true,
        "owl_carousel": true
    },
    "10007": {
        "name": "Easy top",
        "price": 109,
        "description": "try new Branded top shirt buy it very very good  buy it go go go some text try again 10007",
        "category": "t_shirt",
        "color": ['black'],
        "size": ["S", "XS"],
        "image": "../images/pic6.jpg",
        "featured": true,
        "owl_carousel": true
    },
    "10008": {
        "name": "Geox BR01",
        "price": 90,
        "description": "pokupaem new bransed shoes go check sizes and color id 10008",
        "category": "shoes",
        "color": ['brown'],
        "brand" : "Geox",
        "size": [43, 45, 46],
        "image": "../images/c1.jpg",
        "featured": true,
        "owl_carousel": true
    },
    "10009": {
        "name": "Branded tees",
        "price": 79,
        "description": "try new Branded tees buy it very very good  buy it go go go some text try again 10009",
        "category": "t_shirt",
        "color": ['black'],
        "size": ["S", "XS"],
        "image": "../images/c2.jpg",
        "featured": false,
        "owl_carousel": true
    },
    "10010": {
        "name": "Branded jeens",
        "price": 69,
        "description": "try new jeens buy it very very good  buy it go go go some text try again 10010",
        "category": "jeens",
        "color": ['blue'],
        "size": ["M", "XS"],
        "image": "../images/c3.jpg",
        "featured": false,
        "owl_carousel": true
    },
    "10011": {
        "name": "Branded tees",
        "price": 79,
        "description": "try new Branded tees buy it very very good  buy it go go go some text try again 10011",
        "category": "t_shirt",
        "color": ['black'],
        "size": ["L", "M", "S", "XS"],
        "image": "../images/c2.jpg",
        "featured": false,
        "owl_carousel": true
    },
    "10012": {
        "name": "Fly T134",
        "price": 150,
        "description": "pokupaem new bransed shoes go check sizes and color id 10012",
        "category": "shoes",
        "brand" : "Fly",
        "model" : "T100",
        "color": ['black', 'brown', 'lightbrown'],
        "size": [40, 41],
        "image": "../images/shoe_pic1.jpg",
        "featured": false,
        "owl_carousel": false
    },
    "10013": {
        "name": "Fly T135",
        "price": 150,
        "description": "pokupaem new bransed shoes go check sizes and color id 10013",
        "category": "shoes",
        "brand" : "Fly",
        "model" : "T100",
        "color": ['brown', 'black', 'lightbrown'],
        "size": [40, 41, 42, 45, 46],
        "image": "../images/shoe_pic2.jpg",
        "featured": false,
        "owl_carousel": false
    },
    "10014": {
        "name": "Fly T136",
        "price": 150,
        "description": "pokupaem new bransed shoes go check sizes and color id 10014",
        "category": "shoes",
        "brand" : "Fly",
        "model" : "T100",
        "color": ['lightbrown', 'brown', 'black'],
        "size": [42, 45, 46],
        "image": "../images/shoe_pic3.jpg",
        "featured": false,
        "owl_carousel": false
    },
    "10015": {
        "name": "Moko F001",
        "price": 110,
        "description": "pokupaem new bransed shoes go check sizes and color id 10015",
        "category": "shoes",
        "brand" : "Moko",
        "model" : "F000",
        "color": ['brown', 'coffee'],
        "size": [40, 42, 45, 46],
        "image": "../images/shoe_pic4.jpg",
        "featured": false,
        "owl_carousel": false
    },
    "10016": {
        "name": "Moko F002",
        "price": 110,
        "description": "pokupaem new bransed shoes go check sizes and color id 10016",
        "category": "shoes",
        "brand" : "Moko",
        "model" : "F000",
        "color": ['coffee', 'brown'],
        "size": [43, 44, 45],
        "image": "../images/shoe_pic5.jpg",
        "featured": false,
        "owl_carousel": false
    }
};