export const goods = [
    {
        "id": 10001,
        "name": "Branded shoes",
        "price": 100,
        "description": "pokupaem new bransed shoes go check sizes and color id 10001",
        "category" : "shoes",
        "color" : ['red', 'white'],
        "size" : [39, 36],
        "image": "../images/pic1.jpg",
        "featured": true,
        "owl_carousel": false
    },
    {
        "id": 10002,
        "name": "Levis T-shirt",
        "price": 70,
        "description": "try new Levis T-shirtt buy it very very good  buy it go go go some text try again 10002",
        "category" : "t_shirt",
        "color" : ['black', 'blue', 'white'],
        "size" : ["L", "M"],
        "image": "../images/pic2.jpg",
        "featured": true,
        "owl_carousel": false
    },
    {
        "id": 10003,
        "name": "True T-shirt",
        "price": 15,
        "description": "try new Branded t-shirt buy it very very good  buy it go go go some text try again 10003",
        "category" : "t_shirt",
        "color" : ['gray'],
        "size" : ["L", "M"],
        "image": "../images/pic3.jpg",
        "featured": true,
        "owl_carousel": false
    },
    {
        "id": 10004,
        "name": "Branded bags",
        "price": 25,
        "description": "very good wallet buy it go go go some text try again 10004",
        "category" : "wallet",
        "color" : ['brown'],
        "size" : ["current"],
        "image": "../images/pic4.jpg",
        "featured": true,
        "owl_carousel": true
    },
    {
        "id": 10005,
        "name": "EMS women bag",
        "price": 105,
        "description": "very good bag buy it go go go some text try again 10005",
        "category" : "handbags",
        "color" : ['coffee'],
        "size" : ["current"],
        "image": "../images/pic5.jpg",
        "featured": true,
        "owl_carousel": true
    },
    {
        "id": 10006,
        "name": "Easy top",
        "price": 10,
        "description": "try new Branded top shirt buy it very very good  buy it go go go some text try again 10006",
        "category" : "t_shirt",
        "color" : ['black'],
        "size" : ["L", "S"],
        "image": "../images/pic6.jpg",
        "featured": true,
        "owl_carousel": true
    },
    {
        "id": 10007,
        "name": "Easy top",
        "price": 109,
        "description": "try new Branded top shirt buy it very very good  buy it go go go some text try again 10007",
        "category" : "t_shirt",
        "color" : ['black'],
        "size" : ["S", "XS"],
        "image": "../images/pic6.jpg",
        "featured": true,
        "owl_carousel": true
    },
    {
        "id": 10008,
        "name": "Branded shoes",
        "price": 99,
        "description": "pokupaem new bransed shoes go check sizes and color id 10008",
        "category" : "shoes",
        "color" : ['brown', 'black'],
        "size" : [43, 46],
        "image": "../images/c1.jpg",
        "featured": true,
        "owl_carousel": true
    },
    {
        "id": 10009,
        "name": "Branded tees",
        "price": 79,
        "description": "try new Branded tees buy it very very good  buy it go go go some text try again 10009",
        "category" : "t_shirt",
        "color" : ['black'],
        "size" : ["S", "XS"],
        "image": "../images/c2.jpg",
        "featured": false,
        "owl_carousel": true
    },
    {
        "id": 10010,
        "name": "Branded jeens",
        "price": 69,
        "description": "try new jeens buy it very very good  buy it go go go some text try again 10010",
        "category" : "jeens",
        "color" : ['blue'],
        "size" : ["M", "XS"],
        "image": "../images/c3.jpg",
        "featured": false,
        "owl_carousel": true
    },
    {
        "id": 10011,
        "name": "Branded tees",
        "price": 79,
        "description": "try new Branded tees buy it very very good  buy it go go go some text try again 10011",
        "category" : "t_shirt",
        "color" : ['black'],
        "size" : ["L", "M", "S", "XS"],
        "image": "../images/c2.jpg",
        "featured": false,
        "owl_carousel": true
    },
    {
        "id": 10012,
        "name": "Branded shoes",
        "price": 150,
        "description": "pokupaem new bransed shoes go check sizes and color id 10012",
        "category" : "shoes",
        "color" : ['red', 'white'],
        "size" : [36, 39],
        "image": "../images/shoe_pic1.jpg",
        "featured": false,
        "owl_carousel": false
    },
    {
        "id": 10013,
        "name": "Branded shoes",
        "price": 170,
        "description": "pokupaem new bransed shoes go check sizes and color id 10013",
        "category" : "shoes",
        "color" : ['red', 'white', 'brown', 'dark'],
        "size" : [39, 40, 41, 42, 45, 46],
        "image": "../images/shoe_pic2.jpg",
        "featured": false,
        "owl_carousel": false
    },
    {
        "id": 10014,
        "name": "Branded shoes",
        "price": 220,
        "description": "pokupaem new bransed shoes go check sizes and color id 10014",
        "category" : "shoes",
        "color" : ['red', 'white', 'brown', 'dark'],
        "size" : [39, 42, 45, 46],
        "image": "../images/shoe_pic3.jpg",
        "featured": false,
        "owl_carousel": false
    },
    {
        "id": 10015,
        "name": "Branded shoes",
        "price": 110,
        "description": "pokupaem new bransed shoes go check sizes and color id 10015",
        "category" : "shoes",
        "color" : ['red', 'white', 'brown', 'dark'],
        "size" : [39, 42, 45, 46],
        "image": "../images/shoe_pic4.jpg",
        "featured": false,
        "owl_carousel": false
    },
    {
        "id": 10016,
        "name": "Branded shoes",
        "price": 113,
        "description": "pokupaem new bransed shoes go check sizes and color id 10016",
        "category" : "shoes",
        "color" : ['white', 'brown', 'dark'],
        "size" : [39, 42, 45],
        "image": "../images/shoe_pic5.jpg",
        "featured": false,
        "owl_carousel": false
    }
];